"""Export runtime + prose-extraction packages from uv.lock without network access."""
from pathlib import Path
import tomllib

root = Path(__file__).resolve().parents[1]
packages = {p["name"]: p for p in tomllib.loads((root / "uv.lock").read_text())["package"]}
project = packages["founder-radar"]
pending = [d["name"] for d in project["dependencies"] + project["optional-dependencies"]["extract"]]
selected = set()
while pending:
    name = pending.pop()
    if name in selected:
        continue
    selected.add(name)
    pending.extend(d["name"] for d in packages[name].get("dependencies", []))
lines = ["# Generated by deploy/export-lock.py from uv.lock (runtime + extract)."]
for name in sorted(selected):
    package = packages[name]
    artifacts = package.get("wheels", []) + ([package["sdist"]] if "sdist" in package else [])
    hashes = sorted({artifact["hash"] for artifact in artifacts})
    if not hashes:
        raise ValueError(f"no pinned artifacts for {name}")
    lines.append(name + "==" + package["version"] + " " + " ".join("--hash=" + h for h in hashes))
(root / "deploy/requirements.lock").write_text("\n".join(lines) + "\n")
