"""Export runtime + prose-extraction packages from uv.lock without network access."""
from pathlib import Path
import tomllib

root = Path(__file__).resolve().parents[1]
packages = {p["name"]: p for p in tomllib.loads((root / "uv.lock").read_text())["package"]}
project = packages["founder-radar"]
pending = [(d["name"], tuple(d.get("extra", [])))
           for d in project["dependencies"] + project["optional-dependencies"]["extract"]]
selected = set()
visited = set()
while pending:
    name, extras = pending.pop()
    # A package may first arrive without an extra and later with one. Track
    # each request separately so the later optional dependencies are not lost.
    request = (name, extras)
    if request in visited:
        continue
    visited.add(request)
    selected.add(name)
    package = packages[name]
    dependencies = list(package.get("dependencies", []))
    for extra in extras:
        dependencies.extend(package.get("optional-dependencies", {})[extra])
    pending.extend((d["name"], tuple(d.get("extra", []))) for d in dependencies)
lines = ["# Generated by deploy/export-lock.py from uv.lock (runtime + extract)."]
for name in sorted(selected):
    package = packages[name]
    artifacts = package.get("wheels", []) + ([package["sdist"]] if "sdist" in package else [])
    hashes = sorted({artifact["hash"] for artifact in artifacts})
    if not hashes:
        raise ValueError(f"no pinned artifacts for {name}")
    lines.append(name + "==" + package["version"] + " " + " ".join("--hash=" + h for h in hashes))
(root / "deploy/requirements.lock").write_text("\n".join(lines) + "\n")
